/* Generated by Yosys 0.11 (git sha1 360fed8e4, gcc 9.4.0-1ubuntu1~20.04 -fPIC -Os) */

(* src = "custom_cpu_mips.v:4.1-56.10" *)
module alu_golden(A, B, ALUop, Overflow, CarryOut, Zero, Result);
  (* src = "custom_cpu_mips.v:41.18-41.40" *)
  wire [32:0] _00_;
  (* src = "custom_cpu_mips.v:40.16-40.30" *)
  wire [31:0] _01_;
  (* src = "custom_cpu_mips.v:40.33-40.47" *)
  wire [31:0] _02_;
  (* src = "custom_cpu_mips.v:47.20-47.54" *)
  wire _03_;
  (* src = "custom_cpu_mips.v:47.59-47.79" *)
  wire _04_;
  (* src = "custom_cpu_mips.v:49.23-49.44" *)
  wire _05_;
  (* src = "custom_cpu_mips.v:49.23-49.56" *)
  wire _06_;
  (* src = "custom_cpu_mips.v:49.19-49.67" *)
  wire [31:0] _07_;
  (* src = "custom_cpu_mips.v:50.30-50.63" *)
  wire _08_;
  (* src = "custom_cpu_mips.v:50.26-50.73" *)
  wire [31:0] _09_;
  (* src = "custom_cpu_mips.v:51.30-51.51" *)
  wire _10_;
  (* src = "custom_cpu_mips.v:51.30-51.63" *)
  wire _11_;
  (* src = "custom_cpu_mips.v:51.26-51.74" *)
  wire [31:0] _12_;
  (* src = "custom_cpu_mips.v:52.30-52.63" *)
  wire _13_;
  (* src = "custom_cpu_mips.v:52.26-52.74" *)
  wire [31:0] _14_;
  (* src = "custom_cpu_mips.v:53.31-53.51" *)
  wire _15_;
  (* src = "custom_cpu_mips.v:53.26-53.68" *)
  wire [31:0] _16_;
  (* src = "custom_cpu_mips.v:54.34-54.53" *)
  wire _17_;
  (* src = "custom_cpu_mips.v:54.34-54.62" *)
  wire _18_;
  (* src = "custom_cpu_mips.v:40.28-40.30" *)
  wire [31:0] _19_;
  (* src = "custom_cpu_mips.v:40.37-40.41" *)
  wire _20_;
  (* src = "custom_cpu_mips.v:43.21-43.40" *)
  wire _21_;
  (* src = "custom_cpu_mips.v:47.59-47.68" *)
  wire _22_;
  (* src = "custom_cpu_mips.v:49.23-49.32" *)
  wire _23_;
  (* src = "custom_cpu_mips.v:49.47-49.56" *)
  wire _24_;
  (* src = "custom_cpu_mips.v:49.19-50.73" *)
  wire [31:0] _25_;
  (* src = "custom_cpu_mips.v:49.18-52.75" *)
  wire [31:0] _26_;
  (* src = "custom_cpu_mips.v:51.26-52.74" *)
  wire [31:0] _27_;
  (* src = "custom_cpu_mips.v:53.26-54.63" *)
  wire [31:0] _28_;
  (* src = "custom_cpu_mips.v:45.17-45.25" *)
  wire _29_;
  (* src = "custom_cpu_mips.v:43.23-43.39" *)
  wire _30_;
  (* src = "custom_cpu_mips.v:43.44-43.67" *)
  wire _31_;
  (* src = "custom_cpu_mips.v:47.32-47.53" *)
  wire _32_;
  (* src = "custom_cpu_mips.v:5.19-5.20" *)
  input [31:0] A;
  (* src = "custom_cpu_mips.v:7.14-7.19" *)
  input [2:0] ALUop;
  (* src = "custom_cpu_mips.v:6.19-6.20" *)
  input [31:0] B;
  (* src = "custom_cpu_mips.v:9.9-9.17" *)
  output CarryOut;
  (* src = "custom_cpu_mips.v:8.9-8.17" *)
  output Overflow;
  (* src = "custom_cpu_mips.v:11.20-11.26" *)
  output [31:0] Result;
  (* src = "custom_cpu_mips.v:10.9-10.13" *)
  output Zero;
  (* src = "custom_cpu_mips.v:30.18-30.24" *)
  wire [32:0] addres;
  (* src = "custom_cpu_mips.v:25.18-25.24" *)
  wire [31:0] andres;
  (* src = "custom_cpu_mips.v:32.10-32.13" *)
  wire cin;
  (* src = "custom_cpu_mips.v:29.18-29.22" *)
  wire [31:0] comB;
  (* src = "custom_cpu_mips.v:28.18-28.24" *)
  wire [31:0] norres;
  (* src = "custom_cpu_mips.v:26.18-26.23" *)
  wire [31:0] orres;
  (* src = "custom_cpu_mips.v:31.10-31.16" *)
  wire sltres;
  (* src = "custom_cpu_mips.v:27.18-27.24" *)
  wire [31:0] xorres;
  assign _00_ = A + (* src = "custom_cpu_mips.v:41.18-41.40" *) comB;
  assign addres = _00_ + (* src = "custom_cpu_mips.v:41.18-41.46" *) cin;
  assign andres = A & (* src = "custom_cpu_mips.v:34.18-34.23" *) B;
  assign _01_ = { cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin, cin } & (* src = "custom_cpu_mips.v:40.16-40.30" *) _19_;
  assign _02_ = { _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_, _20_ } & (* src = "custom_cpu_mips.v:40.33-40.47" *) B;
  assign Overflow = _21_ & (* src = "custom_cpu_mips.v:43.21-43.68" *) _31_;
  assign _03_ = ALUop[2] & (* src = "custom_cpu_mips.v:47.20-47.54" *) _32_;
  assign _04_ = _22_ & (* src = "custom_cpu_mips.v:47.59-47.79" *) CarryOut;
  assign _05_ = _23_ & (* src = "custom_cpu_mips.v:49.23-49.44" *) _22_;
  assign _06_ = _05_ & (* src = "custom_cpu_mips.v:49.23-49.56" *) _24_;
  assign _07_ = { _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_, _06_ } & (* src = "custom_cpu_mips.v:49.19-49.67" *) andres;
  assign _08_ = _05_ & (* src = "custom_cpu_mips.v:50.30-50.63" *) ALUop[0];
  assign _09_ = { _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_, _08_ } & (* src = "custom_cpu_mips.v:50.26-50.73" *) orres;
  assign _10_ = _23_ & (* src = "custom_cpu_mips.v:51.30-51.51" *) ALUop[2];
  assign _11_ = _10_ & (* src = "custom_cpu_mips.v:51.30-51.63" *) _24_;
  assign _12_ = { _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_, _11_ } & (* src = "custom_cpu_mips.v:51.26-51.74" *) xorres;
  assign _13_ = _10_ & (* src = "custom_cpu_mips.v:52.30-52.63" *) ALUop[0];
  assign _14_ = { _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_, _13_ } & (* src = "custom_cpu_mips.v:52.26-52.74" *) norres;
  assign _15_ = ALUop[1] & (* src = "custom_cpu_mips.v:53.31-53.51" *) _24_;
  assign _16_ = { _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_, _15_ } & (* src = "custom_cpu_mips.v:53.26-53.68" *) addres[31:0];
  assign _17_ = ALUop[1] & (* src = "custom_cpu_mips.v:54.34-54.53" *) ALUop[0];
  assign _18_ = _17_ & (* src = "custom_cpu_mips.v:54.34-54.62" *) sltres;
  assign Zero = ! (* src = "custom_cpu_mips.v:45.17-45.25" *) _29_;
  assign norres = ~ (* src = "custom_cpu_mips.v:37.18-37.24" *) orres;
  assign _19_ = ~ (* src = "custom_cpu_mips.v:40.28-40.30" *) B;
  assign _20_ = ~ (* src = "custom_cpu_mips.v:40.37-40.41" *) cin;
  assign _21_ = ~ (* src = "custom_cpu_mips.v:43.21-43.40" *) _30_;
  assign _22_ = ~ (* src = "custom_cpu_mips.v:47.59-47.68" *) ALUop[2];
  assign _23_ = ~ (* src = "custom_cpu_mips.v:49.23-49.32" *) ALUop[1];
  assign _24_ = ~ (* src = "custom_cpu_mips.v:49.47-49.56" *) ALUop[0];
  assign orres = A | (* src = "custom_cpu_mips.v:35.17-35.22" *) B;
  assign cin = ALUop[2] | (* src = "custom_cpu_mips.v:39.15-39.34" *) ALUop[0];
  assign comB = _01_ | (* src = "custom_cpu_mips.v:40.16-40.47" *) _02_;
  assign sltres = _03_ | (* src = "custom_cpu_mips.v:47.19-47.80" *) _04_;
  assign _25_ = _07_ | (* src = "custom_cpu_mips.v:49.19-50.73" *) _09_;
  assign _26_ = _25_ | (* src = "custom_cpu_mips.v:49.18-52.75" *) _27_;
  assign Result = _26_ | (* src = "custom_cpu_mips.v:49.18-54.64" *) _28_;
  assign _27_ = _12_ | (* src = "custom_cpu_mips.v:51.26-52.74" *) _14_;
  assign _28_ = _16_ | (* src = "custom_cpu_mips.v:53.26-54.63" *) _18_;
  assign _29_ = | (* src = "custom_cpu_mips.v:45.17-45.25" *) Result;
  assign xorres = A ^ (* src = "custom_cpu_mips.v:36.18-36.23" *) B;
  assign _30_ = A[31] ^ (* src = "custom_cpu_mips.v:43.23-43.39" *) comB[31];
  assign _31_ = addres[32] ^ (* src = "custom_cpu_mips.v:43.44-43.67" *) addres[31];
  assign CarryOut = cin ^ (* src = "custom_cpu_mips.v:44.21-44.37" *) addres[32];
  assign _32_ = Overflow ^ (* src = "custom_cpu_mips.v:47.32-47.53" *) addres[31];
endmodule

(* top =  1  *)
(* src = "custom_cpu_mips.v:112.1-596.10" *)
module custom_cpu_golden(rst, clk, PC, Inst_Req_Valid, Inst_Req_Ready, Instruction, Inst_Valid, Inst_Ready, Address, MemWrite, Write_data, Write_strb, MemRead, Mem_Req_Ready, Read_data, Read_data_Valid, Read_data_Ready, cpu_perf_cnt_0, cpu_perf_cnt_1, cpu_perf_cnt_2, cpu_perf_cnt_3
, cpu_perf_cnt_4, cpu_perf_cnt_5, cpu_perf_cnt_6, cpu_perf_cnt_7, cpu_perf_cnt_8, cpu_perf_cnt_9, cpu_perf_cnt_10, cpu_perf_cnt_11, cpu_perf_cnt_12, cpu_perf_cnt_13, cpu_perf_cnt_14, cpu_perf_cnt_15, inst_retire);
  (* src = "custom_cpu_mips.v:411.2-426.5" *)
  wire [31:0] _000_;
  (* src = "custom_cpu_mips.v:403.2-408.5" *)
  wire [31:0] _001_;
  (* src = "custom_cpu_mips.v:445.2-454.5" *)
  wire [31:0] _002_;
  (* src = "custom_cpu_mips.v:387.2-400.5" *)
  wire [31:0] _003_;
  (* src = "custom_cpu_mips.v:325.2-330.5" *)
  wire [8:0] _004_;
  (* src = "custom_cpu_mips.v:493.2-498.5" *)
  wire [31:0] _005_;
  (* src = "custom_cpu_mips.v:429.2-434.5" *)
  wire [31:0] _006_;
  (* src = "custom_cpu_mips.v:437.2-442.5" *)
  wire [31:0] _007_;
  (* src = "custom_cpu_mips.v:521.2-526.5" *)
  wire [31:0] _008_;
  (* src = "custom_cpu_mips.v:548.2-553.5" *)
  wire [31:0] _009_;
  (* src = "custom_cpu_mips.v:578.2-583.5" *)
  wire [31:0] _010_;
  (* src = "custom_cpu_mips.v:502.2-507.5" *)
  wire [31:0] _011_;
  (* src = "custom_cpu_mips.v:539.2-544.5" *)
  wire [31:0] _012_;
  (* src = "custom_cpu_mips.v:530.2-535.5" *)
  wire [31:0] _013_;
  (* src = "custom_cpu_mips.v:511.2-516.5" *)
  wire [31:0] _014_;
  (* src = "custom_cpu_mips.v:566.2-571.5" *)
  wire [31:0] _015_;
  (* src = "custom_cpu_mips.v:572.2-577.5" *)
  wire [31:0] _016_;
  (* src = "custom_cpu_mips.v:560.2-565.5" *)
  wire [31:0] _017_;
  (* src = "custom_cpu_mips.v:587.2-592.5" *)
  wire [31:0] _018_;
  wire [7:0] _019_;
  (* src = "custom_cpu_mips.v:333.2-383.12" *)
  wire [8:0] _020_;
  wire [2:0] _021_;
  wire [3:0] _022_;
  wire [4:0] _023_;
  (* src = "custom_cpu_mips.v:333.2-383.12" *)
  wire [8:0] _024_;
  (* src = "custom_cpu_mips.v:333.2-383.12" *)
  wire [8:0] _025_;
  wire [6:0] _026_;
  wire [6:0] _027_;
  wire [3:0] _028_;
  (* src = "custom_cpu_mips.v:497.17-497.34" *)
  wire [31:0] _029_;
  (* src = "custom_cpu_mips.v:506.33-506.66" *)
  wire [31:0] _030_;
  (* src = "custom_cpu_mips.v:515.28-515.56" *)
  wire [31:0] _031_;
  (* src = "custom_cpu_mips.v:525.28-525.56" *)
  wire [31:0] _032_;
  (* src = "custom_cpu_mips.v:534.26-534.52" *)
  wire [31:0] _033_;
  (* src = "custom_cpu_mips.v:543.25-543.50" *)
  wire [31:0] _034_;
  (* src = "custom_cpu_mips.v:552.30-552.60" *)
  wire [31:0] _035_;
  (* src = "custom_cpu_mips.v:564.35-564.70" *)
  wire [31:0] _036_;
  (* src = "custom_cpu_mips.v:570.32-570.64" *)
  wire [31:0] _037_;
  (* src = "custom_cpu_mips.v:576.29-576.80" *)
  wire [31:0] _038_;
  (* src = "custom_cpu_mips.v:591.20-591.40" *)
  wire [31:0] _039_;
  (* src = "custom_cpu_mips.v:222.19-222.39" *)
  wire _040_;
  (* src = "custom_cpu_mips.v:222.43-222.61" *)
  wire _041_;
  (* src = "custom_cpu_mips.v:223.43-223.61" *)
  wire _042_;
  (* src = "custom_cpu_mips.v:225.19-225.38" *)
  wire _043_;
  (* src = "custom_cpu_mips.v:227.19-227.38" *)
  wire _044_;
  (* src = "custom_cpu_mips.v:234.19-234.40" *)
  wire _045_;
  (* src = "custom_cpu_mips.v:240.17-240.51" *)
  wire _046_;
  (* src = "custom_cpu_mips.v:241.6-241.56" *)
  wire _047_;
  (* src = "custom_cpu_mips.v:242.7-242.28" *)
  wire _048_;
  (* src = "custom_cpu_mips.v:242.33-242.56" *)
  wire _049_;
  (* src = "custom_cpu_mips.v:242.6-242.57" *)
  wire _050_;
  (* src = "custom_cpu_mips.v:258.31-258.54" *)
  wire _051_;
  (* src = "custom_cpu_mips.v:258.28-258.68" *)
  wire [3:0] _052_;
  (* src = "custom_cpu_mips.v:259.46-259.69" *)
  wire _053_;
  (* src = "custom_cpu_mips.v:259.43-259.83" *)
  wire [3:0] _054_;
  (* src = "custom_cpu_mips.v:260.43-260.83" *)
  wire [3:0] _055_;
  (* src = "custom_cpu_mips.v:261.47-261.69" *)
  wire _056_;
  (* src = "custom_cpu_mips.v:261.43-261.99" *)
  wire [3:0] _057_;
  (* src = "custom_cpu_mips.v:262.47-262.69" *)
  wire _058_;
  (* src = "custom_cpu_mips.v:262.43-262.93" *)
  wire [3:0] _059_;
  (* src = "custom_cpu_mips.v:263.20-263.56" *)
  wire [7:0] _060_;
  (* src = "custom_cpu_mips.v:264.38-264.64" *)
  wire _061_;
  (* src = "custom_cpu_mips.v:264.35-264.81" *)
  wire [7:0] _062_;
  (* src = "custom_cpu_mips.v:265.38-265.69" *)
  wire _063_;
  (* src = "custom_cpu_mips.v:265.38-265.82" *)
  wire _064_;
  (* src = "custom_cpu_mips.v:265.91-265.110" *)
  wire _065_;
  (* src = "custom_cpu_mips.v:265.118-265.137" *)
  wire _066_;
  (* src = "custom_cpu_mips.v:265.35-265.140" *)
  wire [7:0] _067_;
  (* src = "custom_cpu_mips.v:266.20-266.56" *)
  wire [7:0] _068_;
  (* src = "custom_cpu_mips.v:267.38-267.64" *)
  wire _069_;
  (* src = "custom_cpu_mips.v:267.35-267.81" *)
  wire [7:0] _070_;
  (* src = "custom_cpu_mips.v:268.38-268.69" *)
  wire _071_;
  (* src = "custom_cpu_mips.v:268.38-268.82" *)
  wire _072_;
  (* src = "custom_cpu_mips.v:268.35-268.140" *)
  wire [7:0] _073_;
  (* src = "custom_cpu_mips.v:269.20-269.55" *)
  wire [7:0] _074_;
  (* src = "custom_cpu_mips.v:270.38-270.64" *)
  wire _075_;
  (* src = "custom_cpu_mips.v:270.35-270.80" *)
  wire [7:0] _076_;
  (* src = "custom_cpu_mips.v:271.38-271.69" *)
  wire _077_;
  (* src = "custom_cpu_mips.v:271.38-271.78" *)
  wire _078_;
  (* src = "custom_cpu_mips.v:271.38-271.91" *)
  wire _079_;
  (* src = "custom_cpu_mips.v:272.20-272.54" *)
  wire [7:0] _080_;
  (* src = "custom_cpu_mips.v:273.35-273.71" *)
  wire [7:0] _081_;
  (* src = "custom_cpu_mips.v:275.21-275.70" *)
  wire [31:0] _082_;
  (* src = "custom_cpu_mips.v:275.73-275.97" *)
  wire [31:0] _083_;
  (* src = "custom_cpu_mips.v:276.21-276.50" *)
  wire [4:0] _084_;
  (* src = "custom_cpu_mips.v:276.67-276.83" *)
  wire [4:0] _085_;
  (* src = "custom_cpu_mips.v:277.42-277.72" *)
  wire _086_;
  (* src = "custom_cpu_mips.v:280.66-280.107" *)
  wire _087_;
  (* src = "custom_cpu_mips.v:281.20-281.38" *)
  wire [31:0] _088_;
  (* src = "custom_cpu_mips.v:281.45-281.65" *)
  wire _089_;
  (* src = "custom_cpu_mips.v:281.41-281.75" *)
  wire [31:0] _090_;
  (* src = "custom_cpu_mips.v:283.8-283.51" *)
  wire _091_;
  (* src = "custom_cpu_mips.v:285.24-285.49" *)
  wire _092_;
  (* src = "custom_cpu_mips.v:285.20-285.59" *)
  wire [31:0] _093_;
  (* src = "custom_cpu_mips.v:286.11-286.36" *)
  wire _094_;
  (* src = "custom_cpu_mips.v:286.7-286.46" *)
  wire [31:0] _095_;
  (* src = "custom_cpu_mips.v:287.12-287.36" *)
  wire _096_;
  (* src = "custom_cpu_mips.v:287.7-287.50" *)
  wire [31:0] _097_;
  (* src = "custom_cpu_mips.v:288.12-288.36" *)
  wire _098_;
  (* src = "custom_cpu_mips.v:288.7-288.57" *)
  wire [31:0] _099_;
  (* src = "custom_cpu_mips.v:289.18-289.73" *)
  wire [2:0] _100_;
  (* src = "custom_cpu_mips.v:290.5-298.77" *)
  wire [2:0] _101_;
  (* src = "custom_cpu_mips.v:291.9-291.47" *)
  wire [2:0] _102_;
  (* src = "custom_cpu_mips.v:292.30-292.72" *)
  wire [2:0] _103_;
  (* src = "custom_cpu_mips.v:293.30-293.60" *)
  wire [2:0] _104_;
  (* src = "custom_cpu_mips.v:294.30-294.62" *)
  wire [2:0] _105_;
  (* src = "custom_cpu_mips.v:295.30-295.61" *)
  wire [2:0] _106_;
  (* src = "custom_cpu_mips.v:296.30-296.63" *)
  wire [2:0] _107_;
  (* src = "custom_cpu_mips.v:297.30-297.65" *)
  wire [2:0] _108_;
  (* src = "custom_cpu_mips.v:298.30-298.74" *)
  wire [2:0] _109_;
  (* src = "custom_cpu_mips.v:301.24-301.43" *)
  wire _110_;
  (* src = "custom_cpu_mips.v:301.20-301.62" *)
  wire [31:0] _111_;
  (* src = "custom_cpu_mips.v:301.69-301.87" *)
  wire _112_;
  (* src = "custom_cpu_mips.v:301.65-301.97" *)
  wire [31:0] _113_;
  (* src = "custom_cpu_mips.v:301.100-301.123" *)
  wire [31:0] _114_;
  (* src = "custom_cpu_mips.v:302.20-302.42" *)
  wire [31:0] _115_;
  (* src = "custom_cpu_mips.v:302.45-302.74" *)
  wire [31:0] _116_;
  (* src = "custom_cpu_mips.v:310.23-310.80" *)
  wire [31:0] _117_;
  (* src = "custom_cpu_mips.v:310.83-310.139" *)
  wire [31:0] _118_;
  (* src = "custom_cpu_mips.v:311.25-311.75" *)
  wire [3:0] _119_;
  (* src = "custom_cpu_mips.v:312.40-312.90" *)
  wire [3:0] _120_;
  (* src = "custom_cpu_mips.v:314.40-314.96" *)
  wire [3:0] _121_;
  (* src = "custom_cpu_mips.v:315.40-315.90" *)
  wire [3:0] _122_;
  (* src = "custom_cpu_mips.v:353.58-353.77" *)
  wire _123_;
  (* src = "custom_cpu_mips.v:355.35-355.53" *)
  wire _124_;
  (* src = "custom_cpu_mips.v:357.13-357.33" *)
  wire _125_;
  (* src = "custom_cpu_mips.v:359.41-359.62" *)
  wire _126_;
  (* src = "custom_cpu_mips.v:390.11-390.43" *)
  wire _127_;
  (* src = "custom_cpu_mips.v:392.11-392.41" *)
  wire _128_;
  (* src = "custom_cpu_mips.v:394.11-394.39" *)
  wire _129_;
  (* src = "custom_cpu_mips.v:396.12-396.40" *)
  wire _130_;
  (* src = "custom_cpu_mips.v:396.11-396.63" *)
  wire _131_;
  (* src = "custom_cpu_mips.v:398.11-398.41" *)
  wire _132_;
  (* src = "custom_cpu_mips.v:398.11-398.50" *)
  wire _133_;
  (* src = "custom_cpu_mips.v:415.7-415.30" *)
  wire _134_;
  (* src = "custom_cpu_mips.v:448.11-448.49" *)
  wire _135_;
  (* src = "custom_cpu_mips.v:514.11-514.54" *)
  wire _136_;
  (* src = "custom_cpu_mips.v:524.11-524.41" *)
  wire _137_;
  (* src = "custom_cpu_mips.v:533.11-533.41" *)
  wire _138_;
  (* src = "custom_cpu_mips.v:533.11-533.53" *)
  wire _139_;
  (* src = "custom_cpu_mips.v:542.11-542.54" *)
  wire _140_;
  (* src = "custom_cpu_mips.v:551.11-551.72" *)
  wire _141_;
  (* src = "custom_cpu_mips.v:573.6-573.61" *)
  wire _142_;
  (* src = "custom_cpu_mips.v:575.11-575.69" *)
  wire _143_;
  wire _144_;
  (* src = "custom_cpu_mips.v:333.2-383.12" *)
  wire [8:0] _145_;
  (* src = "custom_cpu_mips.v:277.19-277.38" *)
  wire _146_;
  (* src = "custom_cpu_mips.v:280.21-280.40" *)
  wire _147_;
  (* src = "custom_cpu_mips.v:280.43-280.62" *)
  wire _148_;
  (* src = "custom_cpu_mips.v:280.66-280.85" *)
  wire _149_;
  (* src = "custom_cpu_mips.v:319.23-319.43" *)
  wire _150_;
  (* src = "custom_cpu_mips.v:320.51-320.71" *)
  wire _151_;
  (* src = "custom_cpu_mips.v:581.11-581.48" *)
  wire _152_;
  (* src = "custom_cpu_mips.v:221.28-221.39" *)
  wire _153_;
  (* src = "custom_cpu_mips.v:222.28-222.39" *)
  wire _154_;
  (* src = "custom_cpu_mips.v:229.19-229.32" *)
  wire _155_;
  (* src = "custom_cpu_mips.v:230.19-230.32" *)
  wire _156_;
  (* src = "custom_cpu_mips.v:237.19-237.32" *)
  wire _157_;
  (* src = "custom_cpu_mips.v:238.19-238.32" *)
  wire _158_;
  (* src = "custom_cpu_mips.v:567.12-567.31" *)
  wire _159_;
  (* src = "custom_cpu_mips.v:573.28-573.61" *)
  wire _160_;
  (* src = "custom_cpu_mips.v:575.33-575.69" *)
  wire _161_;
  (* src = "custom_cpu_mips.v:223.53-223.61" *)
  wire _162_;
  (* src = "custom_cpu_mips.v:225.30-225.38" *)
  wire _163_;
  (* src = "custom_cpu_mips.v:226.41-226.49" *)
  wire _164_;
  (* src = "custom_cpu_mips.v:234.30-234.40" *)
  wire _165_;
  (* src = "custom_cpu_mips.v:234.43-234.53" *)
  wire _166_;
  (* src = "custom_cpu_mips.v:241.19-241.29" *)
  wire _167_;
  (* src = "custom_cpu_mips.v:242.33-242.45" *)
  wire _168_;
  (* src = "custom_cpu_mips.v:242.48-242.56" *)
  wire _169_;
  (* src = "custom_cpu_mips.v:244.34-244.44" *)
  wire _170_;
  (* src = "custom_cpu_mips.v:245.40-245.47" *)
  wire _171_;
  (* src = "custom_cpu_mips.v:264.38-264.56" *)
  wire _172_;
  (* src = "custom_cpu_mips.v:267.38-267.56" *)
  wire _173_;
  (* src = "custom_cpu_mips.v:270.38-270.56" *)
  wire _174_;
  (* src = "custom_cpu_mips.v:273.38-273.56" *)
  wire _175_;
  (* src = "custom_cpu_mips.v:277.75-277.84" *)
  wire _176_;
  (* src = "custom_cpu_mips.v:281.45-281.53" *)
  wire _177_;
  (* src = "custom_cpu_mips.v:285.24-285.35" *)
  wire _178_;
  (* src = "custom_cpu_mips.v:285.38-285.49" *)
  wire _179_;
  (* src = "custom_cpu_mips.v:295.45-295.53" *)
  wire _180_;
  (* src = "custom_cpu_mips.v:310.27-310.33" *)
  wire _181_;
  (* src = "custom_cpu_mips.v:348.36-348.40" *)
  wire _182_;
  (* src = "custom_cpu_mips.v:359.52-359.62" *)
  wire _183_;
  (* src = "custom_cpu_mips.v:240.17-241.56" *)
  wire _184_;
  (* src = "custom_cpu_mips.v:241.34-241.55" *)
  wire _185_;
  (* src = "custom_cpu_mips.v:258.28-259.83" *)
  wire [3:0] _186_;
  (* src = "custom_cpu_mips.v:258.27-260.83" *)
  wire [3:0] _187_;
  (* src = "custom_cpu_mips.v:258.26-261.99" *)
  wire [3:0] _188_;
  (* src = "custom_cpu_mips.v:263.20-264.81" *)
  wire [7:0] _189_;
  (* src = "custom_cpu_mips.v:265.88-265.139" *)
  wire [7:0] _190_;
  (* src = "custom_cpu_mips.v:266.20-267.81" *)
  wire [7:0] _191_;
  (* src = "custom_cpu_mips.v:269.20-270.80" *)
  wire [7:0] _192_;
  (* src = "custom_cpu_mips.v:276.24-276.43" *)
  wire _193_;
  (* src = "custom_cpu_mips.v:276.21-276.64" *)
  wire [4:0] _194_;
  (* src = "custom_cpu_mips.v:277.42-277.84" *)
  wire _195_;
  (* src = "custom_cpu_mips.v:280.21-280.62" *)
  wire _196_;
  (* src = "custom_cpu_mips.v:280.89-280.106" *)
  wire _197_;
  (* src = "custom_cpu_mips.v:282.27-282.90" *)
  wire _198_;
  (* src = "custom_cpu_mips.v:282.20-283.58" *)
  wire [1:0] _199_;
  (* src = "custom_cpu_mips.v:285.20-286.46" *)
  wire [31:0] _200_;
  (* src = "custom_cpu_mips.v:285.20-287.50" *)
  wire [31:0] _201_;
  (* src = "custom_cpu_mips.v:290.8-290.49" *)
  wire _202_;
  (* src = "custom_cpu_mips.v:291.9-292.72" *)
  wire [2:0] _203_;
  (* src = "custom_cpu_mips.v:291.8-294.63" *)
  wire [2:0] _204_;
  (* src = "custom_cpu_mips.v:291.7-298.76" *)
  wire [2:0] _205_;
  (* src = "custom_cpu_mips.v:293.30-294.62" *)
  wire [2:0] _206_;
  (* src = "custom_cpu_mips.v:295.30-296.63" *)
  wire [2:0] _207_;
  (* src = "custom_cpu_mips.v:295.29-298.75" *)
  wire [2:0] _208_;
  (* src = "custom_cpu_mips.v:297.33-297.52" *)
  wire _209_;
  (* src = "custom_cpu_mips.v:297.30-298.74" *)
  wire [2:0] _210_;
  (* src = "custom_cpu_mips.v:298.33-298.52" *)
  wire _211_;
  (* src = "custom_cpu_mips.v:298.33-298.61" *)
  wire _212_;
  (* src = "custom_cpu_mips.v:301.20-301.97" *)
  wire [31:0] _213_;
  (* src = "custom_cpu_mips.v:310.27-310.53" *)
  wire _214_;
  (* src = "custom_cpu_mips.v:311.25-312.90" *)
  wire [3:0] _215_;
  (* src = "custom_cpu_mips.v:311.24-313.81" *)
  wire [3:0] _216_;
  (* src = "custom_cpu_mips.v:314.40-315.90" *)
  wire [3:0] _217_;
  (* src = "custom_cpu_mips.v:353.37-353.54" *)
  wire _218_;
  (* src = "custom_cpu_mips.v:353.36-353.77" *)
  wire _219_;
  (* src = "custom_cpu_mips.v:355.14-355.31" *)
  wire _220_;
  (* src = "custom_cpu_mips.v:355.13-355.53" *)
  wire _221_;
  (* src = "custom_cpu_mips.v:415.7-415.41" *)
  wire _222_;
  (* src = "custom_cpu_mips.v:505.11-505.52" *)
  wire _223_;
  (* src = "custom_cpu_mips.v:505.11-505.74" *)
  wire _224_;
  (* src = "custom_cpu_mips.v:505.11-505.97" *)
  wire _225_;
  (* src = "custom_cpu_mips.v:514.34-514.53" *)
  wire _226_;
  (* src = "custom_cpu_mips.v:551.34-551.62" *)
  wire _227_;
  (* src = "custom_cpu_mips.v:551.34-551.71" *)
  wire _228_;
  (* src = "custom_cpu_mips.v:561.6-561.31" *)
  wire _229_;
  (* src = "custom_cpu_mips.v:567.6-567.31" *)
  wire _230_;
  wire [31:0] _231_;
  wire [31:0] _232_;
  wire [31:0] _233_;
  wire [31:0] _234_;
  wire [31:0] _235_;
  wire [31:0] _236_;
  wire [31:0] _237_;
  wire [31:0] _238_;
  wire [31:0] _239_;
  wire [31:0] _240_;
  wire [31:0] _241_;
  wire [31:0] _242_;
  wire [31:0] _243_;
  wire [31:0] _244_;
  wire [31:0] _245_;
  wire [31:0] _246_;
  wire [31:0] _247_;
  wire [31:0] _248_;
  wire [31:0] _249_;
  wire [31:0] _250_;
  wire [31:0] _251_;
  wire [31:0] _252_;
  wire [31:0] _253_;
  (* src = "custom_cpu_mips.v:244.19-244.31" *)
  wire _254_;
  (* src = "custom_cpu_mips.v:415.7-415.19" *)
  wire _255_;
  (* src = "custom_cpu_mips.v:219.19-219.32" *)
  wire _256_;
  (* src = "custom_cpu_mips.v:221.28-221.39" *)
  wire _257_;
  (* src = "custom_cpu_mips.v:222.28-222.39" *)
  wire _258_;
  (* src = "custom_cpu_mips.v:229.19-229.32" *)
  wire _259_;
  (* src = "custom_cpu_mips.v:230.19-230.32" *)
  wire _260_;
  (* src = "custom_cpu_mips.v:237.19-237.32" *)
  wire _261_;
  (* src = "custom_cpu_mips.v:238.19-238.32" *)
  wire _262_;
  (* src = "custom_cpu_mips.v:261.75-261.98" *)
  wire [3:0] _263_;
  (* src = "custom_cpu_mips.v:310.59-310.79" *)
  wire [31:0] _264_;
  (* src = "custom_cpu_mips.v:311.57-311.74" *)
  wire [3:0] _265_;
  (* src = "custom_cpu_mips.v:312.72-312.89" *)
  wire [3:0] _266_;
  (* src = "custom_cpu_mips.v:315.72-315.89" *)
  wire [3:0] _267_;
  (* src = "custom_cpu_mips.v:452.12-452.43" *)
  wire [31:0] _268_;
  (* src = "custom_cpu_mips.v:262.75-262.92" *)
  wire [3:0] _269_;
  (* src = "custom_cpu_mips.v:310.111-310.138" *)
  wire [31:0] _270_;
  (* src = "custom_cpu_mips.v:314.72-314.95" *)
  wire [3:0] _271_;
  (* src = "custom_cpu_mips.v:450.12-450.36" *)
  wire [31:0] _272_;
  (* src = "custom_cpu_mips.v:261.89-261.97" *)
  wire [31:0] _273_;
  (* src = "custom_cpu_mips.v:310.121-310.137" *)
  wire [31:0] _274_;
  (* src = "custom_cpu_mips.v:240.31-240.50" *)
  wire _275_;
  (* src = "custom_cpu_mips.v:277.54-277.71" *)
  wire _276_;
  (* src = "custom_cpu_mips.v:396.45-396.62" *)
  wire _277_;
  (* src = "custom_cpu_mips.v:191.9-191.16" *)
  wire ALUSEL1;
  (* src = "custom_cpu_mips.v:192.13-192.20" *)
  wire [1:0] ALUSEL2;
  (* src = "custom_cpu_mips.v:195.8-195.19" *)
  (* unused_bits = "0" *)
  wire ALUcarryout;
  (* src = "custom_cpu_mips.v:197.14-197.21" *)
  wire [31:0] ALUdest;
  (* src = "custom_cpu_mips.v:193.13-193.18" *)
  wire [2:0] ALUop;
  (* src = "custom_cpu_mips.v:179.18-179.24" *)
  reg [31:0] ALUout;
  (* src = "custom_cpu_mips.v:194.8-194.19" *)
  (* unused_bits = "0" *)
  wire ALUoverflow;
  (* src = "custom_cpu_mips.v:189.14-189.21" *)
  wire [31:0] ALUsrc1;
  (* src = "custom_cpu_mips.v:190.14-190.21" *)
  wire [31:0] ALUsrc2;
  (* src = "custom_cpu_mips.v:196.8-196.15" *)
  wire ALUzero;
  (* src = "custom_cpu_mips.v:127.16-127.23" *)
  output [31:0] Address;
  (* src = "custom_cpu_mips.v:240.8-240.14" *)
  wire Branch;
  (* src = "custom_cpu_mips.v:175.13-175.15" *)
  reg [31:0] IR;
  (* src = "custom_cpu_mips.v:124.9-124.19" *)
  output Inst_Ready;
  (* src = "custom_cpu_mips.v:119.8-119.22" *)
  input Inst_Req_Ready;
  (* src = "custom_cpu_mips.v:118.9-118.23" *)
  output Inst_Req_Valid;
  (* src = "custom_cpu_mips.v:123.8-123.18" *)
  input Inst_Valid;
  (* src = "custom_cpu_mips.v:122.16-122.27" *)
  input [31:0] Instruction;
  (* src = "custom_cpu_mips.v:176.13-176.16" *)
  reg [31:0] MDR;
  (* src = "custom_cpu_mips.v:131.9-131.16" *)
  output MemRead;
  (* src = "custom_cpu_mips.v:128.9-128.17" *)
  output MemWrite;
  (* src = "custom_cpu_mips.v:132.8-132.21" *)
  input Mem_Req_Ready;
  (* src = "custom_cpu_mips.v:117.20-117.22" *)
  output [31:0] PC;
  reg [31:0] PC;
  (* src = "custom_cpu_mips.v:185.14-185.23" *)
  wire [31:0] RF_rdata1;
  (* src = "custom_cpu_mips.v:186.14-186.23" *)
  wire [31:0] RF_rdata2;
  (* src = "custom_cpu_mips.v:183.13-183.21" *)
  wire [4:0] RF_waddr;
  (* src = "custom_cpu_mips.v:184.14-184.22" *)
  wire [31:0] RF_wdata;
  (* src = "custom_cpu_mips.v:182.8-182.14" *)
  wire RF_wen;
  (* src = "custom_cpu_mips.v:135.16-135.25" *)
  input [31:0] Read_data;
  (* src = "custom_cpu_mips.v:137.9-137.24" *)
  output Read_data_Ready;
  (* src = "custom_cpu_mips.v:136.8-136.23" *)
  input Read_data_Valid;
  (* src = "custom_cpu_mips.v:203.14-203.21" *)
  wire [31:0] SHTdest;
  (* src = "custom_cpu_mips.v:202.13-202.18" *)
  wire [1:0] SHTop;
  (* src = "custom_cpu_mips.v:200.14-200.21" *)
  wire [31:0] SHTsrc1;
  (* src = "custom_cpu_mips.v:201.14-201.21" *)
  wire [31:0] SHTsrc2;
  (* src = "custom_cpu_mips.v:129.16-129.26" *)
  output [31:0] Write_data;
  (* src = "custom_cpu_mips.v:130.15-130.25" *)
  output [3:0] Write_strb;
  (* src = "custom_cpu_mips.v:252.14-252.20" *)
  wire [7:0] byte_0;
  (* src = "custom_cpu_mips.v:251.14-251.20" *)
  wire [7:0] byte_1;
  (* src = "custom_cpu_mips.v:250.14-250.20" *)
  wire [7:0] byte_2;
  (* src = "custom_cpu_mips.v:249.14-249.20" *)
  wire [7:0] byte_3;
  (* src = "custom_cpu_mips.v:114.9-114.12" *)
  input clk;
  (* src = "custom_cpu_mips.v:139.16-139.30" *)
  output [31:0] cpu_perf_cnt_0;
  (* src = "custom_cpu_mips.v:140.16-140.30" *)
  output [31:0] cpu_perf_cnt_1;
  (* src = "custom_cpu_mips.v:149.16-149.31" *)
  output [31:0] cpu_perf_cnt_10;
  (* src = "custom_cpu_mips.v:150.16-150.31" *)
  output [31:0] cpu_perf_cnt_11;
  (* src = "custom_cpu_mips.v:151.16-151.31" *)
  output [31:0] cpu_perf_cnt_12;
  (* src = "custom_cpu_mips.v:152.16-152.31" *)
  output [31:0] cpu_perf_cnt_13;
  (* src = "custom_cpu_mips.v:153.16-153.31" *)
  output [31:0] cpu_perf_cnt_14;
  (* src = "custom_cpu_mips.v:154.16-154.31" *)
  output [31:0] cpu_perf_cnt_15;
  (* src = "custom_cpu_mips.v:141.16-141.30" *)
  output [31:0] cpu_perf_cnt_2;
  (* src = "custom_cpu_mips.v:142.16-142.30" *)
  output [31:0] cpu_perf_cnt_3;
  (* src = "custom_cpu_mips.v:143.16-143.30" *)
  output [31:0] cpu_perf_cnt_4;
  (* src = "custom_cpu_mips.v:144.16-144.30" *)
  output [31:0] cpu_perf_cnt_5;
  (* src = "custom_cpu_mips.v:145.16-145.30" *)
  output [31:0] cpu_perf_cnt_6;
  (* src = "custom_cpu_mips.v:146.16-146.30" *)
  output [31:0] cpu_perf_cnt_7;
  (* src = "custom_cpu_mips.v:147.16-147.30" *)
  output [31:0] cpu_perf_cnt_8;
  (* src = "custom_cpu_mips.v:148.16-148.30" *)
  output [31:0] cpu_perf_cnt_9;
  (* src = "custom_cpu_mips.v:173.12-173.25" *)
  reg [8:0] current_state;
  (* src = "custom_cpu_mips.v:492.13-492.22" *)
  reg [31:0] cycle_cnt;
  (* src = "custom_cpu_mips.v:177.18-177.23" *)
  reg [31:0] data1;
  (* src = "custom_cpu_mips.v:178.18-178.23" *)
  reg [31:0] data2;
  (* src = "custom_cpu_mips.v:245.14-245.23" *)
  wire [31:0] extendimm;
  (* src = "custom_cpu_mips.v:213.13-213.17" *)
  wire [5:0] func;
  (* src = "custom_cpu_mips.v:230.8-230.16" *)
  wire i_typeal;
  (* src = "custom_cpu_mips.v:229.8-229.16" *)
  wire i_typebr;
  (* src = "custom_cpu_mips.v:231.8-231.16" *)
  wire i_typefm;
  (* src = "custom_cpu_mips.v:234.8-234.14" *)
  wire ialgth;
  (* src = "custom_cpu_mips.v:235.8-235.14" *)
  wire icmpst;
  (* src = "custom_cpu_mips.v:233.8-233.14" *)
  wire ilogic;
  (* src = "custom_cpu_mips.v:214.14-214.17" *)
  wire [15:0] imm;
  (* src = "custom_cpu_mips.v:519.13-519.33" *)
  reg [31:0] itype_algor_Inst_cnt;
  (* src = "custom_cpu_mips.v:238.8-238.14" *)
  wire j_type;
  (* src = "custom_cpu_mips.v:547.13-547.35" *)
  reg [31:0] jumpandbranch_Inst_cnt;
  wire [1:0] mask;
  (* src = "custom_cpu_mips.v:559.13-559.26" *)
  reg [31:0] max_cycle_cnt;
  (* src = "custom_cpu_mips.v:501.13-501.38" *)
  reg [31:0] mem_acc_waiting_cycle_cnt;
  (* src = "custom_cpu_mips.v:538.13-538.30" *)
  reg [31:0] mem_read_Inst_cnt;
  (* src = "custom_cpu_mips.v:529.13-529.31" *)
  reg [31:0] mem_write_Inst_cnt;
  (* src = "custom_cpu_mips.v:248.8-248.13" *)
  wire merge;
  (* src = "custom_cpu_mips.v:253.14-253.28" *)
  wire [3:0] mtr_write_strb;
  (* src = "custom_cpu_mips.v:174.12-174.22" *)
  wire [8:0] next_state;
  (* src = "custom_cpu_mips.v:208.13-208.19" *)
  wire [5:0] opcode;
  (* src = "custom_cpu_mips.v:219.8-219.14" *)
  wire r_type;
  (* src = "custom_cpu_mips.v:220.8-220.16" *)
  wire r_typeal;
  (* src = "custom_cpu_mips.v:223.8-223.16" *)
  wire r_typejp;
  (* src = "custom_cpu_mips.v:222.8-222.16" *)
  wire r_typemv;
  (* src = "custom_cpu_mips.v:221.8-221.16" *)
  wire r_typesh;
  (* src = "custom_cpu_mips.v:226.8-226.14" *)
  wire ralgth;
  (* src = "custom_cpu_mips.v:227.8-227.14" *)
  wire rcmpst;
  (* src = "custom_cpu_mips.v:211.13-211.15" *)
  wire [4:0] rd;
  (* src = "custom_cpu_mips.v:237.8-237.14" *)
  wire regimm;
  (* src = "custom_cpu_mips.v:225.8-225.14" *)
  wire rlogic;
  (* src = "custom_cpu_mips.v:209.13-209.15" *)
  wire [4:0] rs;
  (* src = "custom_cpu_mips.v:113.9-113.12" *)
  input rst;
  (* src = "custom_cpu_mips.v:210.13-210.15" *)
  wire [4:0] rt;
  (* src = "custom_cpu_mips.v:510.13-510.33" *)
  reg [31:0] rtype_algor_Inst_cnt;
  (* src = "custom_cpu_mips.v:212.13-212.18" *)
  wire [4:0] shamt;
  (* src = "custom_cpu_mips.v:557.13-557.37" *)
  reg [31:0] single_Inst_IF_cycle_cnt;
  (* src = "custom_cpu_mips.v:558.13-558.34" *)
  reg [31:0] single_Inst_cycle_cnt;
  (* src = "custom_cpu_mips.v:556.13-556.40" *)
  reg [31:0] single_Inst_nonIF_cycle_cnt;
  (* src = "custom_cpu_mips.v:215.14-215.20" *)
  wire [25:0] target;
  (* src = "custom_cpu_mips.v:586.13-586.25" *)
  reg [31:0] tot_Inst_cnt;
  (* src = "custom_cpu_mips.v:244.8-244.14" *)
  wire unsign;
  output [69:0] inst_retire;
  assign _029_ = cycle_cnt + (* src = "custom_cpu_mips.v:497.17-497.34" *) 1'h1;
  assign _030_ = mem_acc_waiting_cycle_cnt + (* src = "custom_cpu_mips.v:506.33-506.66" *) 1'h1;
  assign _031_ = rtype_algor_Inst_cnt + (* src = "custom_cpu_mips.v:515.28-515.56" *) 1'h1;
  assign _032_ = itype_algor_Inst_cnt + (* src = "custom_cpu_mips.v:525.28-525.56" *) 1'h1;
  assign _033_ = mem_write_Inst_cnt + (* src = "custom_cpu_mips.v:534.26-534.52" *) 1'h1;
  assign _034_ = mem_read_Inst_cnt + (* src = "custom_cpu_mips.v:543.25-543.50" *) 1'h1;
  assign _035_ = jumpandbranch_Inst_cnt + (* src = "custom_cpu_mips.v:552.30-552.60" *) 1'h1;
  assign _036_ = single_Inst_nonIF_cycle_cnt + (* src = "custom_cpu_mips.v:564.35-564.70" *) 1'h1;
  assign _037_ = single_Inst_IF_cycle_cnt + (* src = "custom_cpu_mips.v:570.32-570.64" *) 1'h1;
  assign _038_ = single_Inst_nonIF_cycle_cnt + (* src = "custom_cpu_mips.v:576.29-576.80" *) single_Inst_cycle_cnt;
  assign _039_ = tot_Inst_cnt + (* src = "custom_cpu_mips.v:591.20-591.40" *) 1'h1;
  assign r_typeal = r_type & (* src = "custom_cpu_mips.v:220.19-220.37" *) IR[5];
  assign r_typesh = r_type & (* src = "custom_cpu_mips.v:221.19-221.39" *) _153_;
  assign _040_ = r_type & (* src = "custom_cpu_mips.v:222.19-222.39" *) _154_;
  assign _041_ = IR[3] & (* src = "custom_cpu_mips.v:222.43-222.61" *) IR[1];
  assign r_typemv = _040_ & (* src = "custom_cpu_mips.v:222.19-222.62" *) _041_;
  assign _042_ = IR[3] & (* src = "custom_cpu_mips.v:223.43-223.61" *) _162_;
  assign r_typejp = _040_ & (* src = "custom_cpu_mips.v:223.19-223.62" *) _042_;
  assign _043_ = r_typeal & (* src = "custom_cpu_mips.v:225.19-225.38" *) _163_;
  assign rlogic = _043_ & (* src = "custom_cpu_mips.v:225.19-225.49" *) IR[2];
  assign ralgth = _043_ & (* src = "custom_cpu_mips.v:226.19-226.49" *) _164_;
  assign _044_ = r_typeal & (* src = "custom_cpu_mips.v:227.19-227.38" *) IR[3];
  assign rcmpst = _044_ & (* src = "custom_cpu_mips.v:227.19-227.49" *) _164_;
  assign i_typebr = _155_ & (* src = "custom_cpu_mips.v:229.19-229.44" *) IR[28];
  assign i_typeal = _156_ & (* src = "custom_cpu_mips.v:230.19-230.44" *) IR[29];
  assign ilogic = i_typeal & (* src = "custom_cpu_mips.v:233.19-233.40" *) IR[28];
  assign _045_ = i_typeal & (* src = "custom_cpu_mips.v:234.19-234.40" *) _165_;
  assign ialgth = _045_ & (* src = "custom_cpu_mips.v:234.19-234.53" *) _166_;
  assign icmpst = _045_ & (* src = "custom_cpu_mips.v:235.19-235.53" *) IR[27];
  assign regimm = _157_ & (* src = "custom_cpu_mips.v:237.19-237.44" *) IR[26];
  assign j_type = _158_ & (* src = "custom_cpu_mips.v:238.19-238.44" *) IR[27];
  assign _046_ = _166_ & (* src = "custom_cpu_mips.v:240.17-240.51" *) _275_;
  assign merge = IR[27] & (* src = "custom_cpu_mips.v:241.7-241.29" *) _167_;
  assign _047_ = merge & (* src = "custom_cpu_mips.v:241.6-241.56" *) _185_;
  assign _048_ = IR[27] & (* src = "custom_cpu_mips.v:242.7-242.28" *) IR[26];
  assign _049_ = _168_ & (* src = "custom_cpu_mips.v:242.33-242.56" *) _169_;
  assign _050_ = _048_ & (* src = "custom_cpu_mips.v:242.6-242.57" *) _049_;
  assign unsign = _254_ & (* src = "custom_cpu_mips.v:244.19-244.44" *) _170_;
  assign extendimm[31] = IR[15] & (* src = "custom_cpu_mips.v:245.30-245.47" *) _171_;
  assign _052_ = { _051_, _051_, _051_, _051_ } & (* src = "custom_cpu_mips.v:258.28-258.68" *) 1'h1;
  assign _054_ = { _053_, _053_, _053_, _053_ } & (* src = "custom_cpu_mips.v:259.43-259.83" *) 2'h3;
  assign _055_ = { _048_, _048_, _048_, _048_ } & (* src = "custom_cpu_mips.v:260.43-260.83" *) 4'hf;
  assign _057_ = { _056_, _056_, _056_, _056_ } & (* src = "custom_cpu_mips.v:261.43-261.99" *) _263_;
  assign _058_ = merge & (* src = "custom_cpu_mips.v:262.47-262.69" *) IR[28];
  assign _059_ = { _058_, _058_, _058_, _058_ } & (* src = "custom_cpu_mips.v:262.43-262.93" *) _269_;
  assign _060_ = { mtr_write_strb[3], mtr_write_strb[3], mtr_write_strb[3], mtr_write_strb[3], mtr_write_strb[3], mtr_write_strb[3], mtr_write_strb[3], mtr_write_strb[3] } & (* src = "custom_cpu_mips.v:263.20-263.56" *) MDR[31:24];
  assign _061_ = _172_ & (* src = "custom_cpu_mips.v:264.38-264.64" *) merge;
  assign _062_ = { _061_, _061_, _061_, _061_, _061_, _061_, _061_, _061_ } & (* src = "custom_cpu_mips.v:264.35-264.81" *) data2[31:24];
  assign _063_ = _172_ & (* src = "custom_cpu_mips.v:265.38-265.69" *) _166_;
  assign _064_ = _063_ & (* src = "custom_cpu_mips.v:265.38-265.82" *) _165_;
  assign _065_ = MDR[7] & (* src = "custom_cpu_mips.v:265.91-265.110" *) _167_;
  assign _066_ = MDR[15] & (* src = "custom_cpu_mips.v:265.118-265.137" *) IR[26];
  assign _067_ = { _064_, _064_, _064_, _064_, _064_, _064_, _064_, _064_ } & (* src = "custom_cpu_mips.v:265.35-265.140" *) _190_;
  assign _068_ = { mtr_write_strb[2], mtr_write_strb[2], mtr_write_strb[2], mtr_write_strb[2], mtr_write_strb[2], mtr_write_strb[2], mtr_write_strb[2], mtr_write_strb[2] } & (* src = "custom_cpu_mips.v:266.20-266.56" *) MDR[23:16];
  assign _069_ = _173_ & (* src = "custom_cpu_mips.v:267.38-267.64" *) merge;
  assign _070_ = { _069_, _069_, _069_, _069_, _069_, _069_, _069_, _069_ } & (* src = "custom_cpu_mips.v:267.35-267.81" *) data2[23:16];
  assign _071_ = _173_ & (* src = "custom_cpu_mips.v:268.38-268.69" *) _166_;
  assign _072_ = _071_ & (* src = "custom_cpu_mips.v:268.38-268.82" *) _165_;
  assign _073_ = { _072_, _072_, _072_, _072_, _072_, _072_, _072_, _072_ } & (* src = "custom_cpu_mips.v:268.35-268.140" *) _190_;
  assign _074_ = { mtr_write_strb[1], mtr_write_strb[1], mtr_write_strb[1], mtr_write_strb[1], mtr_write_strb[1], mtr_write_strb[1], mtr_write_strb[1], mtr_write_strb[1] } & (* src = "custom_cpu_mips.v:269.20-269.55" *) MDR[15:8];
  assign _075_ = _174_ & (* src = "custom_cpu_mips.v:270.38-270.64" *) merge;
  assign _076_ = { _075_, _075_, _075_, _075_, _075_, _075_, _075_, _075_ } & (* src = "custom_cpu_mips.v:270.35-270.80" *) data2[15:8];
  assign _077_ = _174_ & (* src = "custom_cpu_mips.v:271.38-271.69" *) _166_;
  assign _078_ = _077_ & (* src = "custom_cpu_mips.v:271.38-271.78" *) MDR[7];
  assign _079_ = _078_ & (* src = "custom_cpu_mips.v:271.38-271.91" *) _165_;
  assign _080_ = { mtr_write_strb[0], mtr_write_strb[0], mtr_write_strb[0], mtr_write_strb[0], mtr_write_strb[0], mtr_write_strb[0], mtr_write_strb[0], mtr_write_strb[0] } & (* src = "custom_cpu_mips.v:272.20-272.54" *) MDR[7:0];
  assign _081_ = { _175_, _175_, _175_, _175_, _175_, _175_, _175_, _175_ } & (* src = "custom_cpu_mips.v:273.35-273.71" *) data2[7:0];
  assign _082_ = { IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31], IR[31] } & (* src = "custom_cpu_mips.v:275.21-275.70" *) { byte_3, byte_2, byte_1, byte_0 };
  assign _083_ = { _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_, _170_ } & (* src = "custom_cpu_mips.v:275.73-275.97" *) ALUout;
  assign _084_ = { _193_, _193_, _193_, _193_, _193_ } & (* src = "custom_cpu_mips.v:276.21-276.50" *) IR[20:16];
  assign _085_ = { r_type, r_type, r_type, r_type, r_type } & (* src = "custom_cpu_mips.v:276.67-276.83" *) IR[15:11];
  assign _086_ = r_typemv & (* src = "custom_cpu_mips.v:277.42-277.72" *) _276_;
  assign RF_wen = _146_ & (* src = "custom_cpu_mips.v:277.19-277.85" *) _195_;
  assign _087_ = _149_ & (* src = "custom_cpu_mips.v:280.66-280.107" *) _197_;
  assign _088_ = { ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1, ALUSEL1 } & (* src = "custom_cpu_mips.v:281.20-281.38" *) PC;
  assign _089_ = _177_ & (* src = "custom_cpu_mips.v:281.45-281.65" *) _176_;
  assign _090_ = { _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_, _089_ } & (* src = "custom_cpu_mips.v:281.41-281.75" *) data1;
  assign _091_ = _149_ & (* src = "custom_cpu_mips.v:283.8-283.51" *) _193_;
  assign _092_ = _178_ & (* src = "custom_cpu_mips.v:285.24-285.49" *) _179_;
  assign _093_ = { _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_, _092_ } & (* src = "custom_cpu_mips.v:285.20-285.59" *) data2;
  assign _094_ = _178_ & (* src = "custom_cpu_mips.v:286.11-286.36" *) ALUSEL2[0];
  assign _095_ = { _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_, _094_ } & (* src = "custom_cpu_mips.v:286.7-286.46" *) 3'h4;
  assign _096_ = ALUSEL2[1] & (* src = "custom_cpu_mips.v:287.12-287.36" *) _179_;
  assign _097_ = { _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_, _096_ } & (* src = "custom_cpu_mips.v:287.7-287.50" *) { extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], IR[15:0] };
  assign _098_ = ALUSEL2[1] & (* src = "custom_cpu_mips.v:288.12-288.36" *) ALUSEL2[0];
  assign _099_ = { _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_, _098_ } & (* src = "custom_cpu_mips.v:288.7-288.57" *) { extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], IR[15:0], 2'h0 };
  assign _100_ = { _196_, _196_, _196_ } & (* src = "custom_cpu_mips.v:289.18-289.73" *) 2'h2;
  assign _101_ = { _202_, _202_, _202_ } & (* src = "custom_cpu_mips.v:290.5-298.77" *) _205_;
  assign _102_ = { rlogic, rlogic, rlogic } & (* src = "custom_cpu_mips.v:291.9-291.47" *) { IR[1], 1'h0, IR[0] };
  assign _103_ = { ilogic, ilogic, ilogic } & (* src = "custom_cpu_mips.v:292.30-292.72" *) { IR[27], 1'h0, IR[26] };
  assign _104_ = { ralgth, ralgth, ralgth } & (* src = "custom_cpu_mips.v:293.30-293.60" *) { IR[1], 2'h2 };
  assign _105_ = { ialgth, ialgth, ialgth } & (* src = "custom_cpu_mips.v:294.30-294.62" *) { IR[27], 2'h2 };
  assign _106_ = { rcmpst, rcmpst, rcmpst } & (* src = "custom_cpu_mips.v:295.30-295.61" *) { _180_, 2'h3 };
  assign _107_ = { icmpst, icmpst, icmpst } & (* src = "custom_cpu_mips.v:296.30-296.63" *) { _167_, 2'h3 };
  assign _108_ = { _209_, _209_, _209_ } & (* src = "custom_cpu_mips.v:297.30-297.65" *) 3'h6;
  assign _109_ = { _212_, _212_, _212_ } & (* src = "custom_cpu_mips.v:298.30-298.74" *) 2'h2;
  assign _110_ = r_typesh & (* src = "custom_cpu_mips.v:301.24-301.43" *) _164_;
  assign _111_ = { _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_, _110_ } & (* src = "custom_cpu_mips.v:301.20-301.62" *) IR[10:6];
  assign _112_ = r_typesh & (* src = "custom_cpu_mips.v:301.69-301.87" *) IR[2];
  assign _113_ = { _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_, _112_ } & (* src = "custom_cpu_mips.v:301.65-301.97" *) data1;
  assign _114_ = { i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal } & (* src = "custom_cpu_mips.v:301.100-301.123" *) 5'h10;
  assign _115_ = { r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh, r_typesh } & (* src = "custom_cpu_mips.v:302.20-302.42" *) data2;
  assign _116_ = { i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal, i_typeal } & (* src = "custom_cpu_mips.v:302.45-302.74" *) IR[15:0];
  assign SHTop = { r_typesh, r_typesh } & (* src = "custom_cpu_mips.v:303.20-303.45" *) IR[1:0];
  assign _117_ = { _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_, _214_ } & (* src = "custom_cpu_mips.v:310.23-310.80" *) _264_;
  assign _056_ = merge & (* src = "custom_cpu_mips.v:310.87-310.105" *) _165_;
  assign _118_ = { _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_, _056_ } & (* src = "custom_cpu_mips.v:310.83-310.139" *) _270_;
  assign _051_ = _166_ & (* src = "custom_cpu_mips.v:311.28-311.51" *) _167_;
  assign _119_ = { _051_, _051_, _051_, _051_ } & (* src = "custom_cpu_mips.v:311.25-311.75" *) _265_;
  assign _053_ = _166_ & (* src = "custom_cpu_mips.v:312.43-312.66" *) IR[26];
  assign _120_ = { _053_, _053_, _053_, _053_ } & (* src = "custom_cpu_mips.v:312.40-312.90" *) _266_;
  assign _121_ = { _056_, _056_, _056_, _056_ } & (* src = "custom_cpu_mips.v:314.40-314.96" *) _271_;
  assign _122_ = { _058_, _058_, _058_, _058_ } & (* src = "custom_cpu_mips.v:315.40-315.90" *) _267_;
  assign _123_ = j_type & (* src = "custom_cpu_mips.v:353.58-353.77" *) _167_;
  assign _124_ = j_type & (* src = "custom_cpu_mips.v:355.35-355.53" *) IR[26];
  assign _125_ = IR[31] & (* src = "custom_cpu_mips.v:357.13-357.33" *) IR[29];
  assign _126_ = IR[31] & (* src = "custom_cpu_mips.v:359.41-359.62" *) _183_;
  assign _127_ = _147_ & (* src = "custom_cpu_mips.v:390.11-390.43" *) Inst_Valid;
  assign _128_ = _149_ & (* src = "custom_cpu_mips.v:392.11-392.41" *) r_typejp;
  assign _129_ = _149_ & (* src = "custom_cpu_mips.v:394.11-394.39" *) j_type;
  assign _130_ = _149_ & (* src = "custom_cpu_mips.v:396.12-396.40" *) regimm;
  assign _131_ = _130_ & (* src = "custom_cpu_mips.v:396.11-396.63" *) _277_;
  assign _132_ = _149_ & (* src = "custom_cpu_mips.v:398.11-398.41" *) i_typebr;
  assign _133_ = _132_ & (* src = "custom_cpu_mips.v:398.11-398.50" *) Branch;
  assign _134_ = _255_ & (* src = "custom_cpu_mips.v:415.7-415.30" *) i_typeal;
  assign _135_ = _151_ & (* src = "custom_cpu_mips.v:448.11-448.49" *) Read_data_Valid;
  assign _136_ = _148_ & (* src = "custom_cpu_mips.v:514.11-514.54" *) _226_;
  assign _137_ = _148_ & (* src = "custom_cpu_mips.v:524.11-524.41" *) i_typeal;
  assign _138_ = _148_ & (* src = "custom_cpu_mips.v:533.11-533.41" *) IR[31];
  assign _139_ = _138_ & (* src = "custom_cpu_mips.v:533.11-533.53" *) IR[29];
  assign _140_ = _138_ & (* src = "custom_cpu_mips.v:542.11-542.54" *) _183_;
  assign _141_ = _148_ & (* src = "custom_cpu_mips.v:551.11-551.72" *) _228_;
  assign _142_ = _147_ & (* src = "custom_cpu_mips.v:573.6-573.61" *) _160_;
  assign _143_ = Inst_Req_Valid & (* src = "custom_cpu_mips.v:575.11-575.69" *) _161_;
  assign _144_ = | { _150_, _146_ };
  assign _146_ = current_state == (* src = "custom_cpu_mips.v:277.19-277.38" *) 9'h100;
  assign _147_ = current_state == (* src = "custom_cpu_mips.v:280.21-280.40" *) 3'h4;
  assign _148_ = current_state == (* src = "custom_cpu_mips.v:280.43-280.62" *) 4'h8;
  assign _149_ = current_state == (* src = "custom_cpu_mips.v:280.66-280.85" *) 5'h10;
  assign MemRead = current_state == (* src = "custom_cpu_mips.v:306.20-306.39" *) 7'h40;
  assign MemWrite = current_state == (* src = "custom_cpu_mips.v:309.21-309.40" *) 6'h20;
  assign Inst_Req_Valid = current_state == (* src = "custom_cpu_mips.v:318.27-318.46" *) 2'h2;
  assign _150_ = current_state == (* src = "custom_cpu_mips.v:319.23-319.43" *) 1'h1;
  assign _151_ = current_state == (* src = "custom_cpu_mips.v:320.51-320.71" *) 8'h80;
  assign _152_ = single_Inst_cycle_cnt > (* src = "custom_cpu_mips.v:581.11-581.48" *) max_cycle_cnt;
  assign r_type = ! (* src = "custom_cpu_mips.v:219.19-219.32" *) _256_;
  assign _153_ = ! (* src = "custom_cpu_mips.v:221.28-221.39" *) _257_;
  assign _154_ = ! (* src = "custom_cpu_mips.v:222.28-222.39" *) _258_;
  assign _155_ = ! (* src = "custom_cpu_mips.v:229.19-229.32" *) _259_;
  assign _156_ = ! (* src = "custom_cpu_mips.v:230.19-230.32" *) _260_;
  assign _157_ = ! (* src = "custom_cpu_mips.v:237.19-237.32" *) _261_;
  assign _158_ = ! (* src = "custom_cpu_mips.v:238.19-238.32" *) _262_;
  assign _159_ = current_state != (* src = "custom_cpu_mips.v:567.12-567.31" *) 2'h2;
  assign _160_ = | (* src = "custom_cpu_mips.v:573.28-573.61" *) single_Inst_IF_cycle_cnt;
  assign _161_ = | (* src = "custom_cpu_mips.v:575.33-575.69" *) single_Inst_nonIF_cycle_cnt;
  assign _162_ = ~ (* src = "custom_cpu_mips.v:223.53-223.61" *) IR[1];
  assign _163_ = ~ (* src = "custom_cpu_mips.v:225.30-225.38" *) IR[3];
  assign _164_ = ~ (* src = "custom_cpu_mips.v:226.41-226.49" *) IR[2];
  assign _165_ = ~ (* src = "custom_cpu_mips.v:234.30-234.40" *) IR[28];
  assign _166_ = ~ (* src = "custom_cpu_mips.v:234.43-234.53" *) IR[27];
  assign _167_ = ~ (* src = "custom_cpu_mips.v:241.19-241.29" *) IR[26];
  assign _168_ = ~ (* src = "custom_cpu_mips.v:242.33-242.45" *) ALUdest[31];
  assign _169_ = ~ (* src = "custom_cpu_mips.v:242.48-242.56" *) ALUzero;
  assign _170_ = ~ (* src = "custom_cpu_mips.v:244.34-244.44" *) IR[31];
  assign _171_ = ~ (* src = "custom_cpu_mips.v:245.40-245.47" *) unsign;
  assign _172_ = ~ (* src = "custom_cpu_mips.v:264.38-264.56" *) mtr_write_strb[3];
  assign _173_ = ~ (* src = "custom_cpu_mips.v:267.38-267.56" *) mtr_write_strb[2];
  assign _174_ = ~ (* src = "custom_cpu_mips.v:270.38-270.56" *) mtr_write_strb[1];
  assign _175_ = ~ (* src = "custom_cpu_mips.v:273.38-273.56" *) mtr_write_strb[0];
  assign _176_ = ~ (* src = "custom_cpu_mips.v:277.75-277.84" *) r_typemv;
  assign _177_ = ~ (* src = "custom_cpu_mips.v:281.45-281.53" *) ALUSEL1;
  assign _178_ = ~ (* src = "custom_cpu_mips.v:285.24-285.35" *) ALUSEL2[1];
  assign _179_ = ~ (* src = "custom_cpu_mips.v:285.38-285.49" *) ALUSEL2[0];
  assign _180_ = ~ (* src = "custom_cpu_mips.v:295.45-295.53" *) IR[0];
  assign _181_ = ~ (* src = "custom_cpu_mips.v:310.27-310.33" *) merge;
  assign _183_ = ~ (* src = "custom_cpu_mips.v:359.52-359.62" *) IR[29];
  assign _184_ = _046_ | (* src = "custom_cpu_mips.v:240.17-241.56" *) _047_;
  assign Branch = _184_ | (* src = "custom_cpu_mips.v:240.17-242.57" *) _050_;
  assign _185_ = ALUdest[31] | (* src = "custom_cpu_mips.v:241.34-241.55" *) ALUzero;
  assign _186_ = _052_ | (* src = "custom_cpu_mips.v:258.28-259.83" *) _054_;
  assign _187_ = _186_ | (* src = "custom_cpu_mips.v:258.27-260.83" *) _055_;
  assign _188_ = _187_ | (* src = "custom_cpu_mips.v:258.26-261.99" *) _057_;
  assign mtr_write_strb = _188_ | (* src = "custom_cpu_mips.v:258.26-262.93" *) _059_;
  assign _189_ = _060_ | (* src = "custom_cpu_mips.v:263.20-264.81" *) _062_;
  assign byte_3 = _189_ | (* src = "custom_cpu_mips.v:263.19-265.140" *) _067_;
  assign _190_ = { _065_, _065_, _065_, _065_, _065_, _065_, _065_, _065_ } | (* src = "custom_cpu_mips.v:265.88-265.139" *) { _066_, _066_, _066_, _066_, _066_, _066_, _066_, _066_ };
  assign _191_ = _068_ | (* src = "custom_cpu_mips.v:266.20-267.81" *) _070_;
  assign byte_2 = _191_ | (* src = "custom_cpu_mips.v:266.19-268.140" *) _073_;
  assign _192_ = _074_ | (* src = "custom_cpu_mips.v:269.20-270.80" *) _076_;
  assign byte_1 = _192_ | (* src = "custom_cpu_mips.v:269.19-271.93" *) { _079_, _079_, _079_, _079_, _079_, _079_, _079_, _079_ };
  assign byte_0 = _080_ | (* src = "custom_cpu_mips.v:272.20-273.71" *) _081_;
  assign RF_wdata = _082_ | (* src = "custom_cpu_mips.v:275.21-275.97" *) _083_;
  assign _193_ = IR[31] | (* src = "custom_cpu_mips.v:276.24-276.43" *) i_typeal;
  assign _194_ = _084_ | (* src = "custom_cpu_mips.v:276.21-276.64" *) { j_type, j_type, j_type, j_type, j_type };
  assign RF_waddr = _194_ | (* src = "custom_cpu_mips.v:276.21-276.83" *) _085_;
  assign _195_ = _086_ | (* src = "custom_cpu_mips.v:277.42-277.84" *) _176_;
  assign _196_ = _147_ | (* src = "custom_cpu_mips.v:280.21-280.62" *) _148_;
  assign _197_ = r_typejp | (* src = "custom_cpu_mips.v:280.89-280.106" *) j_type;
  assign ALUSEL1 = _196_ | (* src = "custom_cpu_mips.v:280.20-280.107" *) _087_;
  assign ALUsrc1 = _088_ | (* src = "custom_cpu_mips.v:281.20-281.75" *) _090_;
  assign _198_ = _147_ | (* src = "custom_cpu_mips.v:282.27-282.90" *) _087_;
  assign _199_ = _198_ | (* src = "custom_cpu_mips.v:282.20-283.58" *) { _091_, 1'h0 };
  assign ALUSEL2 = _199_ | (* src = "custom_cpu_mips.v:282.20-284.31" *) { _148_, _148_ };
  assign _200_ = _093_ | (* src = "custom_cpu_mips.v:285.20-286.46" *) _095_;
  assign _201_ = _200_ | (* src = "custom_cpu_mips.v:285.20-287.50" *) _097_;
  assign ALUsrc2 = _201_ | (* src = "custom_cpu_mips.v:285.20-288.57" *) _099_;
  assign ALUop = _100_ | (* src = "custom_cpu_mips.v:289.18-298.77" *) _101_;
  assign _202_ = _149_ | (* src = "custom_cpu_mips.v:290.8-290.49" *) _146_;
  assign _203_ = _102_ | (* src = "custom_cpu_mips.v:291.9-292.72" *) _103_;
  assign _204_ = _203_ | (* src = "custom_cpu_mips.v:291.8-294.63" *) _206_;
  assign _205_ = _204_ | (* src = "custom_cpu_mips.v:291.7-298.76" *) _208_;
  assign _206_ = _104_ | (* src = "custom_cpu_mips.v:293.30-294.62" *) _105_;
  assign _207_ = _106_ | (* src = "custom_cpu_mips.v:295.30-296.63" *) _107_;
  assign _208_ = _207_ | (* src = "custom_cpu_mips.v:295.29-298.75" *) _210_;
  assign _209_ = i_typebr | (* src = "custom_cpu_mips.v:297.33-297.52" *) r_typemv;
  assign _210_ = _108_ | (* src = "custom_cpu_mips.v:297.30-298.74" *) _109_;
  assign _211_ = IR[31] | (* src = "custom_cpu_mips.v:298.33-298.52" *) r_typejp;
  assign _212_ = _211_ | (* src = "custom_cpu_mips.v:298.33-298.61" *) j_type;
  assign _213_ = _111_ | (* src = "custom_cpu_mips.v:301.20-301.97" *) _113_;
  assign SHTsrc1 = _213_ | (* src = "custom_cpu_mips.v:301.20-301.123" *) _114_;
  assign SHTsrc2 = _115_ | (* src = "custom_cpu_mips.v:302.20-302.74" *) _116_;
  assign _214_ = _181_ | (* src = "custom_cpu_mips.v:310.27-310.53" *) _058_;
  assign Write_data = _117_ | (* src = "custom_cpu_mips.v:310.23-310.139" *) _118_;
  assign _215_ = _119_ | (* src = "custom_cpu_mips.v:311.25-312.90" *) _120_;
  assign _216_ = _215_ | (* src = "custom_cpu_mips.v:311.24-313.81" *) _055_;
  assign Write_strb = _216_ | (* src = "custom_cpu_mips.v:311.23-315.91" *) _217_;
  assign _217_ = _121_ | (* src = "custom_cpu_mips.v:314.40-315.90" *) _122_;
  assign Inst_Ready = _150_ | (* src = "custom_cpu_mips.v:319.23-319.65" *) _147_;
  assign Read_data_Ready = _150_ | (* src = "custom_cpu_mips.v:320.28-320.71" *) _151_;
  assign _218_ = regimm | (* src = "custom_cpu_mips.v:353.37-353.54" *) i_typebr;
  assign _219_ = _218_ | (* src = "custom_cpu_mips.v:353.36-353.77" *) _123_;
  assign _220_ = r_type | (* src = "custom_cpu_mips.v:355.14-355.31" *) i_typeal;
  assign _221_ = _220_ | (* src = "custom_cpu_mips.v:355.13-355.53" *) _124_;
  assign _222_ = _134_ | (* src = "custom_cpu_mips.v:415.7-415.41" *) r_typesh;
  assign _223_ = Inst_Req_Valid | (* src = "custom_cpu_mips.v:505.11-505.52" *) _147_;
  assign _224_ = _223_ | (* src = "custom_cpu_mips.v:505.11-505.74" *) MemRead;
  assign _225_ = _224_ | (* src = "custom_cpu_mips.v:505.11-505.97" *) _151_;
  assign _226_ = r_typeal | (* src = "custom_cpu_mips.v:514.34-514.53" *) r_typesh;
  assign _227_ = _197_ | (* src = "custom_cpu_mips.v:551.34-551.62" *) i_typebr;
  assign _228_ = _227_ | (* src = "custom_cpu_mips.v:551.34-551.71" *) regimm;
  assign _229_ = rst | (* src = "custom_cpu_mips.v:561.6-561.31" *) Inst_Req_Valid;
  assign _230_ = rst | (* src = "custom_cpu_mips.v:567.6-567.31" *) _159_;
  (* src = "custom_cpu_mips.v:587.2-592.5" *)
  always @(posedge clk)
    tot_Inst_cnt <= _018_;
  (* src = "custom_cpu_mips.v:578.2-583.5" *)
  always @(posedge clk)
    max_cycle_cnt <= _010_;
  (* src = "custom_cpu_mips.v:572.2-577.5" *)
  always @(posedge clk)
    single_Inst_cycle_cnt <= _016_;
  (* src = "custom_cpu_mips.v:566.2-571.5" *)
  always @(posedge clk)
    single_Inst_IF_cycle_cnt <= _015_;
  (* src = "custom_cpu_mips.v:560.2-565.5" *)
  always @(posedge clk)
    single_Inst_nonIF_cycle_cnt <= _017_;
  (* src = "custom_cpu_mips.v:548.2-553.5" *)
  always @(posedge clk)
    jumpandbranch_Inst_cnt <= _009_;
  (* src = "custom_cpu_mips.v:539.2-544.5" *)
  always @(posedge clk)
    mem_read_Inst_cnt <= _012_;
  (* src = "custom_cpu_mips.v:530.2-535.5" *)
  always @(posedge clk)
    mem_write_Inst_cnt <= _013_;
  (* src = "custom_cpu_mips.v:521.2-526.5" *)
  always @(posedge clk)
    itype_algor_Inst_cnt <= _008_;
  (* src = "custom_cpu_mips.v:511.2-516.5" *)
  always @(posedge clk)
    rtype_algor_Inst_cnt <= _014_;
  (* src = "custom_cpu_mips.v:502.2-507.5" *)
  always @(posedge clk)
    mem_acc_waiting_cycle_cnt <= _011_;
  (* src = "custom_cpu_mips.v:493.2-498.5" *)
  always @(posedge clk)
    cycle_cnt <= _005_;
  (* src = "custom_cpu_mips.v:445.2-454.5" *)
  always @(posedge clk)
    MDR <= _002_;
  (* src = "custom_cpu_mips.v:437.2-442.5" *)
  always @(posedge clk)
    data2 <= _007_;
  (* src = "custom_cpu_mips.v:429.2-434.5" *)
  always @(posedge clk)
    data1 <= _006_;
  (* src = "custom_cpu_mips.v:411.2-426.5" *)
  always @(posedge clk)
    ALUout <= _000_;
  (* src = "custom_cpu_mips.v:403.2-408.5" *)
  always @(posedge clk)
    IR <= _001_;
  (* src = "custom_cpu_mips.v:387.2-400.5" *)
  always @(posedge clk)
    PC <= _003_;
  (* src = "custom_cpu_mips.v:325.2-330.5" *)
  always @(posedge clk)
    current_state <= _004_;
  assign _231_ = _148_ ? (* src = "custom_cpu_mips.v:590.11-590.30|custom_cpu_mips.v:590.8-591.41" *) _039_ : tot_Inst_cnt;
  assign _018_ = rst ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:588.6-588.9|custom_cpu_mips.v:588.3-591.41" *) 32'd0 : _231_;
  assign _232_ = _152_ ? (* src = "custom_cpu_mips.v:581.11-581.48|custom_cpu_mips.v:581.8-582.43" *) single_Inst_cycle_cnt : max_cycle_cnt;
  assign _010_ = rst ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:579.6-579.9|custom_cpu_mips.v:579.3-582.43" *) 32'd0 : _232_;
  assign _233_ = _143_ ? (* src = "custom_cpu_mips.v:575.11-575.69|custom_cpu_mips.v:575.8-576.81" *) _038_ : single_Inst_cycle_cnt;
  assign _016_ = _142_ ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:573.6-573.61|custom_cpu_mips.v:573.3-576.81" *) single_Inst_IF_cycle_cnt : _233_;
  assign _015_ = _230_ ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:567.6-567.31|custom_cpu_mips.v:567.3-570.65" *) 32'd0 : _037_;
  assign _017_ = _229_ ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:561.6-561.31|custom_cpu_mips.v:561.3-564.71" *) 32'd0 : _036_;
  assign _234_ = _141_ ? (* src = "custom_cpu_mips.v:551.11-551.72|custom_cpu_mips.v:551.8-552.61" *) _035_ : jumpandbranch_Inst_cnt;
  assign _009_ = rst ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:549.6-549.9|custom_cpu_mips.v:549.3-552.61" *) 32'd0 : _234_;
  assign _235_ = _140_ ? (* src = "custom_cpu_mips.v:542.11-542.54|custom_cpu_mips.v:542.8-543.51" *) _034_ : mem_read_Inst_cnt;
  assign _012_ = rst ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:540.6-540.9|custom_cpu_mips.v:540.3-543.51" *) 32'd0 : _235_;
  assign _236_ = _139_ ? (* src = "custom_cpu_mips.v:533.11-533.53|custom_cpu_mips.v:533.8-534.53" *) _033_ : mem_write_Inst_cnt;
  assign _013_ = rst ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:531.6-531.9|custom_cpu_mips.v:531.3-534.53" *) 32'd0 : _236_;
  assign _237_ = _137_ ? (* src = "custom_cpu_mips.v:524.11-524.41|custom_cpu_mips.v:524.8-525.57" *) _032_ : itype_algor_Inst_cnt;
  assign _008_ = rst ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:522.6-522.9|custom_cpu_mips.v:522.3-525.57" *) 32'd0 : _237_;
  assign _238_ = _136_ ? (* src = "custom_cpu_mips.v:514.11-514.54|custom_cpu_mips.v:514.8-515.57" *) _031_ : rtype_algor_Inst_cnt;
  assign _014_ = rst ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:512.6-512.9|custom_cpu_mips.v:512.3-515.57" *) 32'd0 : _238_;
  assign _239_ = _225_ ? (* src = "custom_cpu_mips.v:505.11-505.97|custom_cpu_mips.v:505.8-506.67" *) _030_ : mem_acc_waiting_cycle_cnt;
  assign _011_ = rst ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:503.6-503.9|custom_cpu_mips.v:503.3-506.67" *) 32'd0 : _239_;
  assign _005_ = rst ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:494.6-494.9|custom_cpu_mips.v:494.3-497.35" *) 32'd0 : _029_;
  assign _240_ = _056_ ? (* src = "custom_cpu_mips.v:451.12-451.30|custom_cpu_mips.v:451.9-452.44" *) _268_ : MDR;
  assign _241_ = _214_ ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:449.7-449.33|custom_cpu_mips.v:449.4-452.44" *) _272_ : _240_;
  assign _242_ = _135_ ? (* src = "custom_cpu_mips.v:448.11-448.49|custom_cpu_mips.v:448.8-453.6" *) _241_ : MDR;
  assign _002_ = rst ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:446.6-446.9|custom_cpu_mips.v:446.3-453.6" *) 32'd0 : _242_;
  assign _007_ = rst ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:438.6-438.9|custom_cpu_mips.v:438.3-441.23" *) 32'd0 : RF_rdata2;
  assign _006_ = rst ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:430.6-430.9|custom_cpu_mips.v:430.3-433.23" *) 32'd0 : RF_rdata1;
  assign _243_ = _196_ ? (* src = "custom_cpu_mips.v:424.11-424.52|custom_cpu_mips.v:424.8-425.22" *) ALUdest : ALUout;
  assign _244_ = i_typebr ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:419.12-419.20|custom_cpu_mips.v:419.9-422.23" *) ALUout : ALUdest;
  assign _245_ = r_typemv ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:417.12-417.20|custom_cpu_mips.v:417.9-422.23" *) data1 : _244_;
  assign _246_ = _222_ ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:415.7-415.41|custom_cpu_mips.v:415.4-422.23" *) SHTdest : _245_;
  assign _247_ = _149_ ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:414.11-414.30|custom_cpu_mips.v:414.8-425.22" *) _246_ : _243_;
  assign _000_ = rst ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:412.6-412.9|custom_cpu_mips.v:412.3-425.22" *) 32'd0 : _247_;
  assign _248_ = _127_ ? (* src = "custom_cpu_mips.v:406.11-406.43|custom_cpu_mips.v:406.8-407.22" *) Instruction : IR;
  assign _001_ = rst ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:404.6-404.9|custom_cpu_mips.v:404.3-407.22" *) 32'd0 : _248_;
  assign _249_ = _133_ ? (* src = "custom_cpu_mips.v:398.11-398.50|custom_cpu_mips.v:398.8-399.17" *) ALUout : PC;
  assign _250_ = _131_ ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:396.11-396.63|custom_cpu_mips.v:396.8-399.17" *) ALUout : _249_;
  assign _251_ = _129_ ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:394.11-394.39|custom_cpu_mips.v:394.8-399.17" *) { PC[31:28], IR[25:0], 2'h0 } : _250_;
  assign _252_ = _128_ ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:392.11-392.41|custom_cpu_mips.v:392.8-399.17" *) data1 : _251_;
  assign _253_ = _127_ ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:390.11-390.43|custom_cpu_mips.v:390.8-399.17" *) ALUdest : _252_;
  assign _003_ = rst ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:388.6-388.9|custom_cpu_mips.v:388.3-399.17" *) 32'd0 : _253_;
  assign _020_ = Read_data_Valid ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:374.36-374.51|custom_cpu_mips.v:374.33-377.58" *) 9'h100 : 9'h080;
  assign _019_ = Mem_Req_Ready ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:369.36-369.49|custom_cpu_mips.v:369.33-372.57" *) 8'h80 : 8'h40;
  assign { _145_[5:4], _028_ } = Mem_Req_Ready ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:364.36-364.49|custom_cpu_mips.v:364.33-367.57" *) 6'h02 : 6'h20;
  assign _027_ = _126_ ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:359.41-359.62|custom_cpu_mips.v:359.38-362.22" *) 7'h40 : 7'h10;
  assign _026_ = _125_ ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:357.13-357.33|custom_cpu_mips.v:357.10-362.22" *) 7'h20 : _027_;
  assign _025_ = _221_ ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:355.13-355.53|custom_cpu_mips.v:355.10-362.22" *) 9'h100 : { 2'h0, _026_ };
  assign _024_ = _219_ ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:353.36-353.77|custom_cpu_mips.v:353.33-362.22" *) 9'h002 : _025_;
  assign _023_ = _182_ ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:348.36-348.40|custom_cpu_mips.v:348.33-351.57" *) 5'h10 : 5'h02;
  assign _022_ = Inst_Valid ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:343.36-343.46|custom_cpu_mips.v:343.33-346.57" *) 4'h8 : 4'h4;
  assign _021_ = Inst_Req_Ready ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:338.36-338.50|custom_cpu_mips.v:338.33-341.57" *) 3'h4 : 3'h2;
  function [8:0] _590_;
    input [8:0] a;
    input [71:0] b;
    input [7:0] s;
    (* full_case = 32'd1 *)
    (* src = "custom_cpu_mips.v:0.0-0.0|custom_cpu_mips.v:334.3-382.24" *)
    (* parallel_case *)
    casez (s)
      8'b???????1:
        _590_ = b[8:0];
      8'b??????1?:
        _590_ = b[17:9];
      8'b?????1??:
        _590_ = b[26:18];
      8'b????1???:
        _590_ = b[35:27];
      8'b???1????:
        _590_ = b[44:36];
      8'b??1?????:
        _590_ = b[53:45];
      8'b?1??????:
        _590_ = b[62:54];
      8'b1???????:
        _590_ = b[71:63];
      default:
        _590_ = a;
    endcase
  endfunction
  assign next_state = _590_(9'h001, { 6'h00, _021_, 5'h00, _022_, 4'h0, _023_, _024_, 3'h0, _145_[5:4], _028_, 1'h0, _019_, _020_, 9'h002 }, { Inst_Req_Valid, _147_, _148_, _149_, MemWrite, MemRead, _151_, _144_ });
  assign _004_ = rst ? (* full_case = 32'd1 *) (* src = "custom_cpu_mips.v:326.6-326.9|custom_cpu_mips.v:326.3-329.32" *) 9'h001 : next_state;
  assign _254_ = & (* src = "custom_cpu_mips.v:244.19-244.31" *) IR[29:28];
  assign _255_ = & (* src = "custom_cpu_mips.v:415.7-415.19" *) IR[29:26];
  assign _182_ = | (* src = "custom_cpu_mips.v:218.14-218.18" *) IR;
  assign _256_ = | (* src = "custom_cpu_mips.v:219.19-219.32" *) IR[31:26];
  assign _257_ = | (* src = "custom_cpu_mips.v:221.28-221.39" *) IR[5:3];
  assign _258_ = | (* src = "custom_cpu_mips.v:222.28-222.39" *) IR[5:4];
  assign _259_ = | (* src = "custom_cpu_mips.v:229.19-229.32" *) IR[31:29];
  assign _260_ = | (* src = "custom_cpu_mips.v:230.19-230.32" *) IR[31:30];
  assign _261_ = | (* src = "custom_cpu_mips.v:237.19-237.32" *) IR[31:27];
  assign _262_ = | (* src = "custom_cpu_mips.v:238.19-238.32" *) IR[31:28];
  assign _263_ = 4'hf << (* src = "custom_cpu_mips.v:261.75-261.98" *) { _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[1:0] };
  assign _264_ = data2 << (* src = "custom_cpu_mips.v:310.59-310.79" *) { ALUout[1:0], 3'h0 };
  assign _265_ = 1'h1 << (* src = "custom_cpu_mips.v:311.57-311.74" *) ALUout[1:0];
  assign _266_ = 2'h3 << (* src = "custom_cpu_mips.v:312.72-312.89" *) ALUout[1:0];
  assign _267_ = 4'hf << (* src = "custom_cpu_mips.v:315.72-315.89" *) ALUout[1:0];
  assign _268_ = Read_data << (* src = "custom_cpu_mips.v:452.12-452.43" *) { _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[4:0] };
  assign _269_ = 4'hf >> (* src = "custom_cpu_mips.v:262.75-262.92" *) ALUout[1:0];
  assign _270_ = data2 >> (* src = "custom_cpu_mips.v:310.111-310.138" *) { _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[4:0] };
  assign _271_ = 4'hf >> (* src = "custom_cpu_mips.v:314.72-314.95" *) { _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[1:0] };
  assign _272_ = Read_data >> (* src = "custom_cpu_mips.v:450.12-450.36" *) { ALUout[1:0], 3'h0 };
  assign { _273_[31], _273_[1:0] } = 2'h3 - (* src = "custom_cpu_mips.v:261.89-261.97" *) ALUout[1:0];
  assign { _274_[31], _274_[4:0] } = 5'h18 - (* src = "custom_cpu_mips.v:310.121-310.137" *) { ALUout[1:0], 3'h0 };
  assign _275_ = IR[26] ^ (* src = "custom_cpu_mips.v:240.31-240.50" *) ALUzero;
  assign _276_ = ALUzero ^ (* src = "custom_cpu_mips.v:277.54-277.71" *) IR[0];
  assign _277_ = data1[31] ^ (* src = "custom_cpu_mips.v:396.45-396.62" *) IR[16];
  (* module_not_derived = 32'd1 *)
  (* src = "custom_cpu_mips.v:459.13-467.3" *)
  alu_golden u_alu_golden (
    .A(ALUsrc1),
    .ALUop(ALUop),
    .B(ALUsrc2),
    .CarryOut(ALUcarryout),
    .Overflow(ALUoverflow),
    .Result(ALUdest),
    .Zero(ALUzero)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "custom_cpu_mips.v:478.18-488.3" *)
  reg_file_golden u_reg_file_golden (
    .clk(clk),
    .raddr1(IR[25:21]),
    .raddr2(IR[20:16]),
    .rdata1(RF_rdata1),
    .rdata2(RF_rdata2),
    .waddr(RF_waddr),
    .wdata(RF_wdata),
    .wen(RF_wen)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "custom_cpu_mips.v:470.17-475.3" *)
  shifter_golden u_shifter_golden (
    .A(SHTsrc1),
    .B(SHTsrc2),
    .Result(SHTdest),
    .Shiftop(SHTop)
  );
  assign { _145_[8:6], _145_[3:0] } = { 3'h0, _028_ };
  assign _273_[30:2] = { _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31], _273_[31] };
  assign _274_[30:5] = { _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31], _274_[31] };
  assign Address = { ALUout[31:2], 2'h0 };
  assign cpu_perf_cnt_0 = cycle_cnt;
  assign cpu_perf_cnt_1 = mem_acc_waiting_cycle_cnt;
  assign cpu_perf_cnt_2 = rtype_algor_Inst_cnt;
  assign cpu_perf_cnt_3 = itype_algor_Inst_cnt;
  assign cpu_perf_cnt_4 = mem_write_Inst_cnt;
  assign cpu_perf_cnt_5 = mem_read_Inst_cnt;
  assign cpu_perf_cnt_6 = jumpandbranch_Inst_cnt;
  assign cpu_perf_cnt_7 = max_cycle_cnt;
  assign cpu_perf_cnt_8 = tot_Inst_cnt;
  assign extendimm[30:0] = { extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], extendimm[31], IR[15:0] };
  assign func = IR[5:0];
  assign i_typefm = IR[31];
  assign imm = IR[15:0];
  assign mask = ALUout[1:0];
  assign opcode = IR[31:26];
  assign rd = IR[15:11];
  assign rs = IR[25:21];
  assign rt = IR[20:16];
  assign shamt = IR[10:6];
  assign target = IR[25:0];
  reg [31:0] commit_pc;
  always @(posedge clk)
    if (Inst_Req_Valid && Inst_Req_Ready)
      commit_pc <= PC;
  assign inst_retire = {RF_wen, RF_waddr, RF_wdata, commit_pc};
endmodule

(* src = "reg_file_golden.v:6.1-23.10" *)
module reg_file_golden(clk, waddr, raddr1, raddr2, wen, wdata, rdata1, rdata2);
  (* src = "reg_file_golden.v:19.3-19.54" *)
  wire [4:0] _00_;
  (* src = "reg_file_golden.v:19.3-19.54" *)
  wire [31:0] _01_;
  (* src = "reg_file_golden.v:19.3-19.54" *)
  wire [31:0] _02_;
  (* src = "reg_file_golden.v:20.28-20.31" *)
  wire [31:0] _03_;
  (* src = "reg_file_golden.v:21.28-21.31" *)
  wire [31:0] _04_;
  (* src = "reg_file_golden.v:20.19-20.43" *)
  wire _05_;
  (* src = "reg_file_golden.v:21.19-21.43" *)
  wire _06_;
  (* src = "reg_file_golden.v:7.30-7.33" *)
  input clk;
  wire clk;
  (* src = "reg_file_golden.v:9.20-9.26" *)
  input [4:0] raddr1;
  wire [4:0] raddr1;
  (* src = "reg_file_golden.v:10.20-10.26" *)
  input [4:0] raddr2;
  wire [4:0] raddr2;
  (* src = "reg_file_golden.v:13.21-13.27" *)
  output [31:0] rdata1;
  wire [31:0] rdata1;
  (* src = "reg_file_golden.v:14.21-14.27" *)
  output [31:0] rdata2;
  wire [31:0] rdata2;
  (* src = "reg_file_golden.v:8.20-8.25" *)
  input [4:0] waddr;
  wire [4:0] waddr;
  (* src = "reg_file_golden.v:12.21-12.26" *)
  input [31:0] wdata;
  wire [31:0] wdata;
  (* src = "reg_file_golden.v:11.30-11.33" *)
  input wen;
  wire wen;
  (* src = "reg_file_golden.v:18.14-18.17" *)
  reg [31:0] ram [31:0];
  always @(posedge clk) begin
    if (_02_[31])
      ram[_00_] <= _01_;
  end
  assign _04_ = ram[raddr2];
  assign _03_ = ram[raddr1];
  assign _02_[31] = wen ? (* full_case = 32'd1 *) (* src = "reg_file_golden.v:19.29-19.32|reg_file_golden.v:19.25-19.54" *) 1'h1 : 1'h0;
  assign _01_ = wen ? (* full_case = 32'd1 *) (* src = "reg_file_golden.v:19.29-19.32|reg_file_golden.v:19.25-19.54" *) wdata : 32'hxxxxxxxx;
  assign _00_ = wen ? (* full_case = 32'd1 *) (* src = "reg_file_golden.v:19.29-19.32|reg_file_golden.v:19.25-19.54" *) waddr : 5'hxx;
  assign _05_ = | (* src = "reg_file_golden.v:20.19-20.43" *) raddr1;
  assign _06_ = | (* src = "reg_file_golden.v:21.19-21.43" *) raddr2;
  assign rdata1 = _05_ ? (* src = "reg_file_golden.v:20.19-20.43" *) _03_ : 32'd0;
  assign rdata2 = _06_ ? (* src = "reg_file_golden.v:21.19-21.43" *) _04_ : 32'd0;
  assign _02_[30:0] = { _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31], _02_[31] };
endmodule

(* src = "custom_cpu_mips.v:88.1-110.10" *)
module shifter_golden(A, B, Shiftop, Result);
  (* src = "custom_cpu_mips.v:107.18-107.58" *)
  wire [31:0] _00_;
  (* src = "custom_cpu_mips.v:108.30-108.54" *)
  wire _01_;
  (* src = "custom_cpu_mips.v:108.25-108.65" *)
  wire [31:0] _02_;
  (* src = "custom_cpu_mips.v:109.30-109.54" *)
  wire _03_;
  (* src = "custom_cpu_mips.v:109.25-109.65" *)
  wire [31:0] _04_;
  (* src = "custom_cpu_mips.v:107.22-107.33" *)
  wire _05_;
  (* src = "custom_cpu_mips.v:109.43-109.54" *)
  wire _06_;
  (* src = "custom_cpu_mips.v:107.18-108.65" *)
  wire [31:0] _07_;
  (* src = "custom_cpu_mips.v:89.19-89.20" *)
  input [31:0] A;
  (* src = "custom_cpu_mips.v:90.19-90.20" *)
  input [31:0] B;
  (* src = "custom_cpu_mips.v:92.20-92.26" *)
  output [31:0] Result;
  (* src = "custom_cpu_mips.v:91.14-91.21" *)
  input [1:0] Shiftop;
  (* src = "custom_cpu_mips.v:100.14-100.20" *)
  wire [31:0] sllres;
  (* src = "custom_cpu_mips.v:101.14-101.20" *)
  wire [31:0] srares;
  (* src = "custom_cpu_mips.v:102.14-102.20" *)
  wire [31:0] srlres;
  assign _00_ = { _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_, _05_ } & (* src = "custom_cpu_mips.v:107.18-107.58" *) sllres;
  assign _01_ = Shiftop[1] & (* src = "custom_cpu_mips.v:108.30-108.54" *) Shiftop[0];
  assign _02_ = { _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_, _01_ } & (* src = "custom_cpu_mips.v:108.25-108.65" *) srares;
  assign _03_ = Shiftop[1] & (* src = "custom_cpu_mips.v:109.30-109.54" *) _06_;
  assign _04_ = { _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_, _03_ } & (* src = "custom_cpu_mips.v:109.25-109.65" *) srlres;
  assign _05_ = ~ (* src = "custom_cpu_mips.v:107.22-107.33" *) Shiftop[1];
  assign _06_ = ~ (* src = "custom_cpu_mips.v:109.43-109.54" *) Shiftop[0];
  assign _07_ = _00_ | (* src = "custom_cpu_mips.v:107.18-108.65" *) _02_;
  assign Result = _07_ | (* src = "custom_cpu_mips.v:107.18-109.65" *) _04_;
  assign sllres = B << (* src = "custom_cpu_mips.v:104.18-104.29" *) A[4:0];
  assign srlres = B >> (* src = "custom_cpu_mips.v:106.18-106.29" *) A[4:0];
  assign srares = $signed(B) >>> (* src = "custom_cpu_mips.v:105.18-105.41" *) A[4:0];
endmodule
